### ISSUE TITLE
accuracy on ucf101 dataset is just 40+%

### ISSUE THREAD

**Issue by 95xueqian** [RI-CH/SlowFastNetworks#3] opened 2019-02-25 01:17 UTC
i have trained the slowfastNetwork on ucf101 dataset，but the accuracy was just 40+% after 80 epochs

**Comment by RI-CH** [comment] 2019-03-04 02:42
40% accuracy was tested on validation dataset, right?
Duplicate of #1

**Closed** 2019-03-04 02:53 UTC

**Comment by 95xueqian** [comment] 2019-03-20 02:00
@RI-CH  the accuracy on train dataset is 78%
